import os
try:
    import openai
    OPENAI_AVAILABLE = True
except ImportError:
    logger.warning("OpenAI library not available. Using fallback methods.")
    OPENAI_AVAILABLE = False
    openai = None

from PyPDF2 import PdfReader
import re
from typing import Dict, List, Optional
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class NeuroLMSAI:
    def __init__(self):
        # Initialize OpenAI client
        if OPENAI_AVAILABLE:
            self.api_key = os.getenv('OPENAI_API_KEY')
            if self.api_key:
                openai.api_key = self.api_key
                self.use_openai = True
            else:
                self.use_openai = False
                logger.warning("OpenAI API key not found. Using fallback methods.")
        else:
            self.use_openai = False
            logger.warning("OpenAI library not available. Using fallback methods.")

    def enhance_script(self, script: str, subject: str = "General") -> str:
        """
        Enhance a teaching script using AI for better educational content
        """
        if self.use_openai:
            return self._enhance_script_openai(script, subject)
        else:
            return self._enhance_script_fallback(script, subject)

    def _enhance_script_openai(self, script: str, subject: str) -> str:
        """Use OpenAI GPT for script enhancement"""
        try:
            prompt = f"""
            You are an expert educational content creator for a Learning Management System.
            Transform the following teaching script into an engaging, structured lesson.

            Subject: {subject}
            Original Script: {script}

            Please create:
            1. An engaging introduction
            2. Clear learning objectives
            3. Structured content breakdown
            4. Key concepts with explanations
            5. Real-world examples
            6. Practice questions
            7. Summary and key takeaways

            Format the response professionally for learners.
            """

            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are an expert educational content creator."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=1500,
                temperature=0.7
            )

            enhanced_content = response.choices[0].message.content.strip()

            return f"""
==============================
🤖 NeuroLMS AI-Enhanced Lesson
==============================

📚 Subject: {subject}

{enhanced_content}

==============================
Generated by NeuroLMS AI
==============================
"""

        except Exception as e:
            logger.error(f"OpenAI enhancement failed: {e}")
            return self._enhance_script_fallback(script, subject)

    def _enhance_script_fallback(self, script: str, subject: str) -> str:
        """Fallback enhancement when OpenAI is not available"""
        return f"""
==============================
🤖 NeuroLMS AI Instructor Mode
==============================

📚 Subject: {subject}

📘 Teaching Introduction:
Welcome learners! Today we'll explore: {script[:100]}...

🎯 Learning Objectives:
• Understand the core concepts
• Apply knowledge in practical scenarios
• Demonstrate comprehension through examples

🧠 Structured Content:
1. Introduction and Context
2. Core Principles and Concepts
3. Detailed Explanations
4. Real-world Applications
5. Common Challenges and Solutions

📌 Key Content:
{script}

🧪 Practice Questions:
1. What are the main concepts discussed?
2. How can you apply this knowledge?
3. What are the key takeaways?
4. How does this relate to real-world scenarios?

📝 Summary:
This lesson covers essential knowledge in {subject}.
Mastery of these concepts will help you succeed in your learning journey.

==============================
Enhanced by NeuroLMS AI
==============================
"""

    def summarize_pdf(self, file_path: str, max_length: int = 1000) -> Dict[str, any]:
        """
        Advanced PDF summarization with AI
        """
        try:
            # Extract text from PDF
            text = self._extract_pdf_text(file_path)
            if not text:
                return {"error": "Could not extract text from PDF"}

            if self.use_openai:
                return self._summarize_pdf_openai(text, max_length)
            else:
                return self._summarize_pdf_fallback(text, max_length)

        except Exception as e:
            logger.error(f"PDF summarization failed: {e}")
            return {"error": f"Failed to process PDF: {str(e)}"}

    def _extract_pdf_text(self, file_path: str) -> str:
        """Extract text from PDF file"""
        try:
            reader = PdfReader(file_path)
            text = ""

            for page in reader.pages:
                page_text = page.extract_text()
                if page_text:
                    text += page_text + "\n"

            return text.strip()
        except Exception as e:
            logger.error(f"PDF text extraction failed: {e}")
            return ""

    def _summarize_pdf_openai(self, text: str, max_length: int) -> Dict[str, any]:
        """Use OpenAI for intelligent PDF summarization"""
        try:
            # Truncate text if too long
            if len(text) > 8000:
                text = text[:8000] + "..."

            prompt = f"""
            Analyze this document and provide:
            1. A concise summary (200-300 words)
            2. Key topics and concepts
            3. Main conclusions or recommendations
            4. 5 multiple-choice quiz questions with answers

            Document content:
            {text}
            """

            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are an expert document analyzer and educational content creator."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=1500,
                temperature=0.5
            )

            analysis = response.choices[0].message.content.strip()

            return {
                "summary": self._extract_section(analysis, "summary"),
                "key_topics": self._extract_section(analysis, "key topics"),
                "conclusions": self._extract_section(analysis, "conclusions"),
                "quiz_questions": self._extract_quiz_questions(analysis),
                "word_count": len(text.split()),
                "ai_generated": True
            }

        except Exception as e:
            logger.error(f"OpenAI PDF analysis failed: {e}")
            return self._summarize_pdf_fallback(text, max_length)

    def _summarize_pdf_fallback(self, text: str, max_length: int) -> Dict[str, any]:
        """Fallback PDF summarization"""
        # Extract key sentences (simple heuristic)
        sentences = re.split(r'[.!?]+', text)
        key_sentences = [s.strip() for s in sentences if len(s.strip()) > 20][:5]

        summary = " ".join(key_sentences)
        if len(summary) > max_length:
            summary = summary[:max_length] + "..."

        return {
            "summary": summary,
            "key_topics": ["Document Analysis", "Content Review", "Educational Material"],
            "conclusions": "Document processed successfully. Key information extracted.",
            "quiz_questions": [
                {"question": "What is the main topic of this document?", "options": ["A", "B", "C", "D"], "answer": "A"},
                {"question": "What are the key concepts discussed?", "options": ["A", "B", "C", "D"], "answer": "B"},
                {"question": "What conclusions can be drawn?", "options": ["A", "B", "C", "D"], "answer": "C"},
                {"question": "How can this information be applied?", "options": ["A", "B", "C", "D"], "answer": "D"},
                {"question": "What are the main takeaways?", "options": ["A", "B", "C", "D"], "answer": "A"}
            ],
            "word_count": len(text.split()),
            "ai_generated": False
        }

    def _extract_section(self, text: str, section_name: str) -> str:
        """Extract a section from AI-generated text"""
        # Simple extraction - in production, use more sophisticated parsing
        lines = text.split('\n')
        section_content = []
        capture = False

        for line in lines:
            if section_name.lower() in line.lower():
                capture = True
                continue
            elif capture and line.strip() and not line[0].isdigit():
                section_content.append(line)
            elif capture and line.strip() and line[0].isdigit():
                break

        return " ".join(section_content).strip() or f"Section about {section_name}"

    def _extract_quiz_questions(self, text: str) -> List[Dict]:
        """Extract quiz questions from AI response"""
        # Simple extraction - in production, use better parsing
        questions = []
        lines = text.split('\n')

        for i, line in enumerate(lines):
            if line.strip().startswith(('1.', '2.', '3.', '4.', '5.')) and '?' in line:
                question = line.strip()
                # Try to get options from next few lines
                options = []
                for j in range(1, 5):
                    if i + j < len(lines):
                        next_line = lines[i + j].strip()
                        if next_line.startswith(('A.', 'B.', 'C.', 'D.')):
                            options.append(next_line)

                questions.append({
                    "question": question,
                    "options": [opt[2:] if len(opt) > 2 else opt for opt in options],
                    "answer": "A"  # Default answer
                })

        return questions if questions else self._get_default_questions()

    def _get_default_questions(self) -> List[Dict]:
        """Return default quiz questions"""
        return [
            {
                "question": "What is the main topic discussed in the document?",
                "options": ["General concepts", "Specific procedures", "Case studies", "All of the above"],
                "answer": "D"
            },
            {
                "question": "What are the key takeaways from this material?",
                "options": ["Important concepts", "Best practices", "Guidelines", "All apply"],
                "answer": "D"
            }
        ]

# Global AI instance
ai_engine = NeuroLMSAI()

# Backward compatibility functions
def enhance_script(script: str) -> str:
    """Legacy function for backward compatibility"""
    return ai_engine.enhance_script(script)

def summarize_pdf(file_path: str) -> str:
    """Legacy function for backward compatibility"""
    result = ai_engine.summarize_pdf(file_path)
    if "error" in result:
        return f"Error: {result['error']}"

    summary = f"""
==============================
🤖 NeuroLMS AI Document Analyzer
==============================

📘 Summary:
{result.get('summary', 'Summary not available')}

🔑 Key Topics:
{', '.join(result.get('key_topics', []))}

📝 Auto Generated Quiz:
"""
    for i, q in enumerate(result.get('quiz_questions', []), 1):
        summary += f"{i}. {q['question']}\n"

    summary += "\n==============================\n"
    return summary